### ISSUE TITLE
Change recursive behaviour

### ISSUE THREAD

**Issue by bjompen** [bjompen/PSSecretScanner#18]
Today we scan repos recursively.
In order to create the console plugin we need to change this behaviour to be recursive on request.

There are two options on how to this:

- `-Recurse` is a switch parameter
  - Pro: PowerShell standard, turn it on if needed
  - Con: Default of is a change in behaviour from today, and one I am not sure I want...
- `-Recurse` is a bool parameter
  - Pro: Can keep default recursive by having it default on
  - Con: May be a bit weird to have to turn it of?

**Comment by jdhitsolutions** [comment]
The correct PowerShell model would be to define this parameter as a  `[Switch]`.  If you want to recurse by default, then change the parameter to `-NoRecurse`.
