### ISSUE TITLE
Find-Secret output

### ISSUE THREAD

**Issue by jdhitsolutions** [bjompen/PSSecretScanner#21]
I think the output for `Find-Secret` should be an object, not an error. If my code is clean, running `Find-Secret` throws an error showing 0 files. This is counterintuitive. An error is when the command can't complete.  The command completes and is not finding anything. That is not an error. That is actually the desired result.

The challenge with this function is that breaks a PowerShell scripting rule, "functions should write one type of object to the pipeline". I think your function should always write a Microsoft.PowerShell.Commands.MatchInfo object to the pipeline. If matches are found, write the message as a Warning. If no strings are found, I would use Write-Host and display a message in Green that no matches were found.
Yes, this would be a breaking change but it would be better PowerShell.

**Comment by bjompen** [comment]
I agree, and it is something I've been thinking of as well, although even better I think would be to manage it like its own object using classes or similar (kind of like Pester does it)

I'll add this to the "2.0" release and make sure ta have a decision in time for that. Thank you!

**Comment by jdhitsolutions** [comment]
Defining your own object is the right way to go. Then you can create custom format views. You could also add your own properties like the path and date of the scan.
