### ISSUE TITLE
Fails to find simple password

### ISSUE THREAD

**Issue by jdhitsolutions** [bjompen/PSSecretScanner#22]
While it shouldn't happen, it is possible for someone to have simple passwords like `FooBarSecret`. This is the type of person that is also likely to store the password in a file. This pattern is missed.

**Comment by bjompen** [comment]
This is an interesting one. Passwords in themselves kind of goes against the original purpose of this module where I searched for patterns of bad strings while actually ignoring the contents of the passwords/keys/secrets, where as this is more "are you using bad passwords" kind of scanning.
I could absolutely add a list of "top 500 bad passwords to scan for", and I do see a good purpose for it, but there are some considerations to take at first:
- This would not be pattern matching as it is done today. We could pretty much use `$_ -like "*$BadPass*"` to find them.
- I still haven't found the time to work in parallelization, so each added pattern adds lots of time. adding a "top 500 bad passwords" would make it unusably slow with todays setup. While this is probably ok in a pipeline or cron job, it would not really work when adding it to the prompt.

I do really like the idea though.. so maybe adding a rainbow table, and either
- Add another command such as `Find-BadPassword` to the module with a similar behaviour
- Add a `-IncludeBadPasswords` switch to Find-Secret to make this scan selectable (and documented increased time to scan.)

Which one of these to go with I would say mostly depends on the imagined scenario (scan in a pipeline makes a parameter make sense, scan my folders/shares manually makes a separate command make more sense I think)

Please let me know what you think, and I'll get working on it.

**Comment by jdhitsolutions** [comment]
I was originally thinking about catching a line of code like `password = 'foobar'` since it appears that `Find-Secret` will detect `password = 'foobar123'`.  But I can totally see value in a `Find-BadPassword` that would check files against a list of known bad passwords. I'd also include a parameter to allow the user to specify their own array of passwords.

**Comment by bjompen** [comment]
oh! That's actually a bug in the pattern I would say. We should of course capture `password = 'foobar'` as well as `password = 'foobar123'`
I'll add it to testcases and see if I can fix it.

**Comment by bjompen** [comment]
After doing some testing and exploration of Find-BadPassword I've come to the conclusion that this is not feasible. Since most bad passwords are actual words (top 10000 known bads) it simply gave an insane amount of false positives for every single repo i tested it on.. Closing this for now.
