### ISSUE TITLE
Configure the module for Core

### ISSUE THREAD

**Issue by jdhitsolutions** [bjompen/PSSecretScanner#3]
The ValidateScript attribute you are using only works in PowerShell 7. As far as I can tell, it is not supported in Windows PowerShell. If you want to use it, you should set the module manifest's `CompatibleEditions` to `Core` and document the requirement in the `README`.

You are also using the new `-AsHashtable` parameter with `ConvertFrom-Json`, another PowerShell 7 feature.

**Comment by bjompen** [comment]
Thanks for letting me know! Sometimes I forget people still use windows powershell.
Updated and pushed version 1.0.5

**Comment by csandfeld** [comment]
We still primarily use Windows PowerShell, so in order to evaluate this module, I forked it, and added support for Windows PowerShell. I just pushed the changes to my fork. Let me know if you want a PR for these changes @bjompen

**Comment by bjompen** [comment]
> We still primarily use Windows PowerShell, so in order to evaluate this module, I forked it, and added support for Windows PowerShell. I just pushed the changes to my fork. Let me know if you want a PR for these changes @bjompen

I like it a lot! As long as we don't export the helper functions I would absolutely like a fully supported version.
(I might rebuild this to a separate files module to make public/private clearer, but that's a future feature ;) )

**Comment by csandfeld** [comment]
> I like it a lot! As long as we don't export the helper functions I would absolutely like a fully supported version. (I might rebuild this to a separate files module to make public/private clearer, but that's a future feature ;) )

Cool. Not exposing helper functions. Will do a PR shortly :)

**Comment by bjompen** [comment]
Merged! Thank you very much!

**Comment by csandfeld** [comment]
> Merged! Thank you very much!

My pleasure
