### ISSUE TITLE
Scan a single file

### ISSUE THREAD

**Issue by jdhitsolutions** [bjompen/PSSecretScanner#6]
I would like the ability to scan a single file. I've tried the existing parameters and can't find a way to do that.

**Comment by bjompen** [comment]
It should work if you use the Path parameter with a single file.
tested on 1.0.6 and on both PS 7 and 5.1
![image](https://user-images.githubusercontent.com/17783007/180263444-0eafc7b3-33a5-4c76-8f42-c814236ac278.png)

Could you give some more details? How does it behave for you?

**Comment by jdhitsolutions** [comment]
I guess it does after all. Never mind. Still, it might be worth noting in the help. I interpreted `Path` to be a folder. It wasn't clear that it could be a file. Your current code also lets the user run a command like `find-secret -path c:\work\test.txt -filetype *.ps1` which doesn't make any sense. You might need to add logic to ignore Filetype if the path is a file. Or use parameters sets.

**Comment by bjompen** [comment]
Absolutely makes sense.. I should probably add a -File parameter that practically does the same thing, but in a ParameterSet, and well documented. Thanks for the idea!
